#define WS2812_DI_PIN GP23
#define RGBLED_NUM 2
#define RGBLED_SPLIT { 1, 1 }

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_RETAIN_VAL

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_ROTATION_90
#define MASTER_RIGHT
